### ISSUE TITLE
equivalent to sangria.marshalling.sprayJson.sprayJsonReaderFromInput?

### ISSUE THREAD

**Issue by evbo** [sangria-graphql/sangria-circe#13]
Hi,

What is the equivalent import for circe for the following sprayJson?:
`import sangria.marshalling.sprayJson.sprayJsonReaderFromInput`

In migrating from sprayJson to circe, I've tried using `import sangria.marshalling.circe.circeFromInput`

But I still get error:
```
Error:(58, 146) Type Option[Seq[Metric @@ sangria.marshalling.FromInput.InputObjectResult]] cannot be used as an input. Please consider defining an implicit instance of `FromInput` for it.
```

Here is how my spray implementation worked:
```
trait InputJsonFormat extends DefaultJsonProtocol {
  implicit val metricFilterFormat = jsonFormat4(Metric)
}

object Resolvers extends InputJsonFormat {

val MetricType = deriveInputObjectType[Metric]()

  val queryType = ObjectType(
    "Query", "Required root object that contains all types",
    fields[Context, Unit](

      Field("getMetrics", ListType(MetricsType),
        arguments = List(Argument("metric", OptionInputType(ListInputType(MetricType)))),
        resolve = c => c.ctx.dao.getMetrics(c.argOpt[Seq[Metric]]("metric"))
      ),
  )
}



```

**Comment by evbo** [comment]
Thank you and sorry for the late response. So it appears that with circe I needed the following import that was missing:

`import sangria.marshalling.circe._`

That's all the magic it took! Now it's compiling, thank you!

**Comment by cristinarc** [comment]
It took me also quite some time to find out that this line was what was missing. Thanks for sharing it!
